[pytest]
DJANGO_SETTINGS_MODULE = wccomps.settings
pythonpath = web
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
testpaths = bot/tests
addopts = -v --tb=short
