"""
Django settings for wccomps project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import secrets
import sys
from pathlib import Path

import django_stubs_ext

django_stubs_ext.monkeypatch()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", secrets.token_urlsafe(50))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")

# CSRF trusted origins for reverse proxy
CSRF_TRUSTED_ORIGINS = [
    "https://bot.wccomps.org",
    "http://bot.wccomps.org",
    "https://register.wccomps.org",
    "http://register.wccomps.org",
    "https://team.wccomps.org",
    "http://team.wccomps.org",
    "https://teams.wccomps.org",
    "http://teams.wccomps.org",
    "https://ticket.wccomps.org",
    "http://ticket.wccomps.org",
    "https://tickets.wccomps.org",
    "http://tickets.wccomps.org",
    "https://portal.wccomps.org",
    "http://portal.wccomps.org",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django_cotton",
    "core",
    "team",
    "ticketing",
    "quotient",
    "scoring",
    "packets",
    "registration",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.SubdomainRedirectMiddleware",
    "core.middleware.AuthentikRequiredMiddleware",
    "core.middleware.AccessLoggingMiddleware",
]

ROOT_URLCONF = "wccomps.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.permissions",
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
            ],
        },
    },
]

WSGI_APPLICATION = "wccomps.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "wccomps"),
        "USER": os.environ.get("DB_USER", "wccomps"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "wccomps"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        # Connection pooling: Reuse connections for 10 minutes
        "CONN_MAX_AGE": 600,
        # Health checks: Verify connection is alive before using
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            # Connection timeout
            "connect_timeout": 10,
            # Statement timeout (30 seconds max per query)
            "options": "-c statement_timeout=30000",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = str(BASE_DIR / "staticfiles")
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = str(BASE_DIR / "media")

# WhiteNoise configuration for serving static files
# Use simple storage for tests (no manifest required)
if "test" in sys.argv or "pytest" in sys.modules:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Trust X-Forwarded-Proto header from reverse proxy (Cloudflare/Traefik)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Security settings for production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Don't redirect to HTTPS - let Traefik handle it
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Sites framework
SITE_ID = 1

# Authentication
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# OAuth configuration (custom Authentik OIDC)
LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Authentik OAuth settings
AUTHENTIK_CLIENT_ID = os.environ.get("AUTHENTIK_CLIENT_ID")
AUTHENTIK_SECRET = os.environ.get("AUTHENTIK_SECRET")
AUTHENTIK_OIDC_URL = os.environ.get(
    "AUTHENTIK_OIDC_URL",
    "https://auth.wccomps.org/application/o/discord-bot/",
)

# Session configuration (12-hour expiry for competitions)
SESSION_COOKIE_AGE = 43200
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SAMESITE = "Lax"  # Allow cookies across OAuth redirects

# WCComps specific settings
BASE_URL = os.environ.get("BASE_URL", "http://localhost:5000")
DISCORD_LOG_CHANNEL_ID = int(os.environ.get("DISCORD_LOG_CHANNEL_ID", "0"))
DISCORD_TICKET_QUEUE_CHANNEL_ID = int(os.environ.get("DISCORD_TICKET_QUEUE_CHANNEL_ID", "1429147071562252360"))
DISCORD_ANNOUNCEMENT_CHANNEL_ID = int(os.environ.get("DISCORD_ANNOUNCEMENT_CHANNEL_ID", "1208127199622860881"))
# Channel where combined link+ticket panel is posted (#welcome-rules)
DISCORD_WELCOME_CHANNEL_ID = int(os.environ.get("DISCORD_WELCOME_CHANNEL_ID", "525724053730885642"))
# Channel where link-only panel is posted (#link - hidden after linking)
DISCORD_LINK_CHANNEL_ID = int(os.environ.get("DISCORD_LINK_CHANNEL_ID", "1436492939130835065"))
BLUETEAM_ROLE_ID = int(os.environ.get("BLUETEAM_ROLE_ID", "525444104763736075"))

# Authentik group to Discord role mappings
BLACKTEAM_ROLE_ID = int(os.environ.get("BLACKTEAM_ROLE_ID", "779192640540639263"))
WHITETEAM_ROLE_ID = int(os.environ.get("WHITETEAM_ROLE_ID", "647838503505362957"))
ORANGETEAM_ROLE_ID = int(os.environ.get("ORANGETEAM_ROLE_ID", "647878925040615446"))
REDTEAM_ROLE_ID = int(os.environ.get("REDTEAM_ROLE_ID", "546490269693116437"))
GOLDTEAM_ROLE_ID = int(os.environ.get("GOLDTEAM_ROLE_ID", "1435254879235997897"))

# Authentik group name to Discord role ID mapping
GROUP_ROLE_MAPPING = {
    "WCComps_BlackTeam": BLACKTEAM_ROLE_ID,
    "WCComps_WhiteTeam": WHITETEAM_ROLE_ID,
    "WCComps_OrangeTeam": ORANGETEAM_ROLE_ID,
    "WCComps_RedTeam": REDTEAM_ROLE_ID,
    "WCComps_GoldTeam": GOLDTEAM_ROLE_ID,
}

# Guild configuration for role synchronization
VOLUNTEER_GUILD_ID = int(os.environ.get("VOLUNTEER_GUILD_ID", "404855247857778697"))
COMPETITION_GUILD_ID = int(os.environ.get("DISCORD_GUILD_ID", "525435725123158026"))  # Main competition guild

# Role sync mappings: Volunteer Guild Role ID -> Competition Guild Role ID
# Sync is one-way: changes in volunteer guild propagate to competition guild
ROLE_SYNC_MAPPING = {
    440383982753021972: BLACKTEAM_ROLE_ID,  # Operations team (BlackTeam)
    440384323863183360: GOLDTEAM_ROLE_ID,  # Gold team
    440384279218749450: REDTEAM_ROLE_ID,  # Red team
    440384105851518978: WHITETEAM_ROLE_ID,  # White team
    440384249061965824: ORANGETEAM_ROLE_ID,  # Orange team
}

AUTHENTIK_URL = os.environ.get("AUTHENTIK_URL", "https://auth.wccomps.org")
AUTHENTIK_TOKEN = os.environ.get("AUTHENTIK_TOKEN", "")

# Quotient API settings
QUOTIENT_API_URL = os.environ.get("QUOTIENT_API_URL", "https://scoring.wccomps.org")

# Quotient authentication (hardcoded admin in event.conf)
QUOTIENT_USERNAME = os.environ.get("QUOTIENT_USERNAME", "")
QUOTIENT_PASSWORD = os.environ.get("QUOTIENT_PASSWORD", "")

# Email configuration for packet distribution
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@wccomps.org")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

# Logging configuration - capture errors to stdout and Discord
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "discord": {
            "class": "core.discord_logging.DiscordWebhookHandler",
            "level": "ERROR",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "discord"],
            "level": "ERROR",
            "propagate": False,
        },
        "wccomps.access": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "wccomps.errors": {
            "handlers": ["console", "discord"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
