# Generated by Django 5.2.11 on 2026-02-21 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Steps/instructions for the orange teamer')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When assignments go live', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orange_check',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrangeCheckCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('points', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('orange_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='challenges.orangecheck')),
            ],
            options={
                'db_table': 'orange_check_criterion',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
