# Generated by Django 5.2.11 on 2026-02-21 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_orangecheck_orangecheckcriterion'),
        ('team', '0006_migrate_helper_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Reviewer notes (for rejections)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orange_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='challenges.orangecheck')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assignments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orange_assignments', to='team.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orange_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orange_assignment',
                'ordering': ['team__team_number'],
            },
        ),
        migrations.CreateModel(
            name='OrangeAssignmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('met', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='challenges.orangeassignment')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='challenges.orangecheckcriterion')),
            ],
            options={
                'db_table': 'orange_assignment_result',
            },
        ),
        migrations.AddConstraint(
            model_name='orangeassignment',
            constraint=models.UniqueConstraint(fields=('orange_check', 'team'), name='one_assignment_per_team_per_check'),
        ),
        migrations.AddConstraint(
            model_name='orangeassignmentresult',
            constraint=models.UniqueConstraint(fields=('assignment', 'criterion'), name='one_result_per_criterion_per_assignment'),
        ),
    ]
