# Generated by Django 5.2.11 on 2026-02-21 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_orangeassignment_orangeassignmentresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='challenges.orangeassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orange_followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orange_followup',
                'ordering': ['remind_at'],
            },
        ),
    ]
