# Generated by Django 5.1.14 on 2025-11-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('assigned_to_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('assigned_to_discord_username', models.CharField(blank=True, max_length=255)),
                ('assigned_to_authentik_username', models.CharField(blank=True, max_length=255)),
                ('assigned_to_authentik_user_id', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('resolved_by_discord_username', models.CharField(blank=True, max_length=255)),
                ('resolved_by_authentik_username', models.CharField(blank=True, max_length=255)),
                ('resolved_by_authentik_user_id', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('duration_notes', models.TextField(blank=True)),
                ('points_charged', models.IntegerField(default=0)),
                ('discord_thread_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('discord_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('thread_archive_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='team.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticketing.ticket')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('comment_text', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('discord_message_id', models.BigIntegerField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticketing.ticket')),
            ],
            options={
                'ordering': ['posted_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('actor_discord_id', models.BigIntegerField(null=True)),
                ('actor_username', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ticketing.ticket')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'status'], name='ticketing_t_team_id_829bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category', 'status'], name='ticketing_t_categor_77881b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to_discord_id'], name='ticketing_t_assigne_4fd9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['discord_thread_id'], name='ticketing_t_discord_341b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='commentratelimit',
            index=models.Index(fields=['ticket', '-posted_at'], name='ticketing_c_ticket__4c5370_idx'),
        ),
        migrations.AddIndex(
            model_name='commentratelimit',
            index=models.Index(fields=['discord_id', '-posted_at'], name='ticketing_c_discord_755fb8_idx'),
        ),
    ]
