# Generated by Django 5.1.14 on 2025-11-29 20:59
# NOTE: This migration has been applied. The person app has been deleted.
# Fields added here were later removed by migration 0005 and replaced with DiscordLink FKs.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0001_initial"),
    ]

    operations = [
        # Fields were added then removed - no-op for fresh databases
        # The person.Person FKs were replaced by team.DiscordLink FKs in migration 0005
    ]
