# Generated by Django 5.0.14 on 2025-11-06 09:17

from django.db import migrations


def copy_ticket_data(apps, schema_editor):
    """Copy data from core app tables to ticketing app tables."""
    # Get models from both apps
    CoreTicket = apps.get_model("core", "Ticket")
    TicketingTicket = apps.get_model("ticketing", "Ticket")

    CoreTicketAttachment = apps.get_model("core", "TicketAttachment")
    TicketingTicketAttachment = apps.get_model("ticketing", "TicketAttachment")

    CoreTicketComment = apps.get_model("core", "TicketComment")
    TicketingTicketComment = apps.get_model("ticketing", "TicketComment")

    CoreTicketHistory = apps.get_model("core", "TicketHistory")
    TicketingTicketHistory = apps.get_model("ticketing", "TicketHistory")

    CoreCommentRateLimit = apps.get_model("core", "CommentRateLimit")
    TicketingCommentRateLimit = apps.get_model("ticketing", "CommentRateLimit")

    # Step 1: Copy Ticket records (has foreign key to team.Team)
    ticket_id_mapping = {}
    for core_ticket in CoreTicket.objects.all():
        new_ticket = TicketingTicket.objects.create(
            id=core_ticket.id,  # Preserve primary key
            ticket_number=core_ticket.ticket_number,
            team_id=core_ticket.team_id,
            category=core_ticket.category,
            title=core_ticket.title,
            description=core_ticket.description,
            hostname=core_ticket.hostname,
            ip_address=core_ticket.ip_address,
            service_name=core_ticket.service_name,
            custom_fields=core_ticket.custom_fields,
            status=core_ticket.status,
            tags=core_ticket.tags,
            assigned_to_discord_id=core_ticket.assigned_to_discord_id,
            assigned_to_discord_username=core_ticket.assigned_to_discord_username,
            assigned_to_authentik_username=core_ticket.assigned_to_authentik_username,
            assigned_to_authentik_user_id=core_ticket.assigned_to_authentik_user_id,
            assigned_at=core_ticket.assigned_at,
            resolved_by_discord_id=core_ticket.resolved_by_discord_id,
            resolved_by_discord_username=core_ticket.resolved_by_discord_username,
            resolved_by_authentik_username=core_ticket.resolved_by_authentik_username,
            resolved_by_authentik_user_id=core_ticket.resolved_by_authentik_user_id,
            resolved_at=core_ticket.resolved_at,
            resolution_notes=core_ticket.resolution_notes,
            duration_notes=core_ticket.duration_notes,
            points_charged=core_ticket.points_charged,
            discord_thread_id=core_ticket.discord_thread_id,
            discord_channel_id=core_ticket.discord_channel_id,
            thread_archive_scheduled_at=core_ticket.thread_archive_scheduled_at,
            created_at=core_ticket.created_at,
            updated_at=core_ticket.updated_at,
        )
        ticket_id_mapping[core_ticket.id] = new_ticket.id

    # Step 2: Copy TicketAttachment records
    for core_attachment in CoreTicketAttachment.objects.all():
        ticket_id = ticket_id_mapping.get(core_attachment.ticket_id)
        if ticket_id:
            TicketingTicketAttachment.objects.create(
                id=core_attachment.id,
                ticket_id=ticket_id,
                file_data=core_attachment.file_data,
                filename=core_attachment.filename,
                mime_type=core_attachment.mime_type,
                uploaded_by=core_attachment.uploaded_by,
                uploaded_at=core_attachment.uploaded_at,
            )

    # Step 3: Copy TicketComment records
    for core_comment in CoreTicketComment.objects.all():
        ticket_id = ticket_id_mapping.get(core_comment.ticket_id)
        if ticket_id:
            TicketingTicketComment.objects.create(
                id=core_comment.id,
                ticket_id=ticket_id,
                author_name=core_comment.author_name,
                author_discord_id=core_comment.author_discord_id,
                comment_text=core_comment.comment_text,
                posted_at=core_comment.posted_at,
                discord_message_id=core_comment.discord_message_id,
            )

    # Step 4: Copy TicketHistory records
    for core_history in CoreTicketHistory.objects.all():
        ticket_id = ticket_id_mapping.get(core_history.ticket_id)
        if ticket_id:
            TicketingTicketHistory.objects.create(
                id=core_history.id,
                ticket_id=ticket_id,
                action=core_history.action,
                actor_discord_id=core_history.actor_discord_id,
                actor_username=core_history.actor_username,
                details=core_history.details,
                timestamp=core_history.timestamp,
            )

    # Step 5: Copy CommentRateLimit records
    for core_rate_limit in CoreCommentRateLimit.objects.all():
        ticket_id = (
            ticket_id_mapping.get(core_rate_limit.ticket_id)
            if core_rate_limit.ticket_id
            else None
        )
        TicketingCommentRateLimit.objects.create(
            id=core_rate_limit.id,
            ticket_id=ticket_id,
            discord_id=core_rate_limit.discord_id,
            posted_at=core_rate_limit.posted_at,
        )


def reverse_copy(apps, schema_editor):
    """Reverse migration - delete copied data from ticketing app."""
    TicketingTicket = apps.get_model("ticketing", "Ticket")
    TicketingTicketAttachment = apps.get_model("ticketing", "TicketAttachment")
    TicketingTicketComment = apps.get_model("ticketing", "TicketComment")
    TicketingTicketHistory = apps.get_model("ticketing", "TicketHistory")
    TicketingCommentRateLimit = apps.get_model("ticketing", "CommentRateLimit")

    # Delete in reverse order of foreign key dependencies
    TicketingCommentRateLimit.objects.all().delete()
    TicketingTicketHistory.objects.all().delete()
    TicketingTicketComment.objects.all().delete()
    TicketingTicketAttachment.objects.all().delete()
    TicketingTicket.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0001_initial"),
        ("core", "0015_initialize_ticket_counters"),
        ("team", "0002_copy_data_from_core"),  # Team data must be copied first
    ]

    operations = [
        migrations.RunPython(copy_ticket_data, reverse_copy),
    ]
