# Generated by Django 5.1.14 on 2025-11-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_helper_activated_at_and_more'),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Person assigned to this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='person.person'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Person who resolved this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to='person.person'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Person who authored this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='person.person'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Person who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='person.person'),
        ),
    ]
