# Generated by Django 5.1.14 on 2025-11-29 21:10
# NOTE: This migration has been applied. The person app has been deleted.
# The RunPython operations are now no-ops since the migration is already in django_migrations.

from django.db import migrations


def noop(apps, schema_editor):
    """No-op - migration already applied, person app deleted."""


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0002_ticket_assigned_to_ticket_resolved_by_and_more"),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
