# Generated by Django 5.1.14 on 2025-11-29 21:10

from django.db import migrations


def get_or_create_person(Person, User, authentik_user_id=None, discord_id=None,
                         authentik_username="", discord_username=""):
    """Find or create a Person by authentik_user_id or discord_id."""
    # Try to find by authentik_user_id first
    if authentik_user_id:
        person = Person.objects.filter(authentik_user_id=authentik_user_id).first()
        if person:
            return person

    # Try to find by discord_id
    if discord_id:
        person = Person.objects.filter(discord_id=discord_id).first()
        if person:
            return person

    # No existing person found - create one if we have identifying info
    if not authentik_user_id and not discord_id:
        return None

    # Create a Django User first (required for Person)
    username = authentik_username or discord_username or f"user_{discord_id or authentik_user_id}"
    # Ensure unique username
    base_username = username[:140]
    counter = 0
    while User.objects.filter(username=username).exists():
        counter += 1
        username = f"{base_username}_{counter}"

    user = User.objects.create(username=username)

    # Create Person directly (signal won't fire in migrations)
    person = Person.objects.create(
        user=user,
        authentik_username=authentik_username or username,
        authentik_user_id=authentik_user_id if authentik_user_id else None,
        discord_id=discord_id if discord_id else None,
        discord_username=discord_username or "",
    )

    return person


def populate_ticket_fks(apps, schema_editor):
    """Populate Person FK fields on Ticket model."""
    Ticket = apps.get_model('ticketing', 'Ticket')
    Person = apps.get_model('person', 'Person')
    User = apps.get_model('auth', 'User')

    for ticket in Ticket.objects.all():
        # Populate assigned_to FK
        if ticket.assigned_to_authentik_user_id or ticket.assigned_to_discord_id:
            person = get_or_create_person(
                Person, User,
                authentik_user_id=ticket.assigned_to_authentik_user_id or None,
                discord_id=ticket.assigned_to_discord_id,
                authentik_username=ticket.assigned_to_authentik_username or "",
                discord_username=ticket.assigned_to_discord_username or "",
            )
            if person:
                ticket.assigned_to = person

        # Populate resolved_by FK
        if ticket.resolved_by_authentik_user_id or ticket.resolved_by_discord_id:
            person = get_or_create_person(
                Person, User,
                authentik_user_id=ticket.resolved_by_authentik_user_id or None,
                discord_id=ticket.resolved_by_discord_id,
                authentik_username=ticket.resolved_by_authentik_username or "",
                discord_username=ticket.resolved_by_discord_username or "",
            )
            if person:
                ticket.resolved_by = person

        ticket.save()


def populate_comment_fks(apps, schema_editor):
    """Populate Person FK fields on TicketComment model."""
    TicketComment = apps.get_model('ticketing', 'TicketComment')
    Person = apps.get_model('person', 'Person')
    User = apps.get_model('auth', 'User')

    for comment in TicketComment.objects.all():
        if comment.author_discord_id:
            person = get_or_create_person(
                Person, User,
                discord_id=comment.author_discord_id,
                discord_username=comment.author_name or "",
            )
            if person:
                comment.author = person
                comment.save()


def populate_history_fks(apps, schema_editor):
    """Populate Person FK fields on TicketHistory model."""
    TicketHistory = apps.get_model('ticketing', 'TicketHistory')
    Person = apps.get_model('person', 'Person')
    User = apps.get_model('auth', 'User')

    for history in TicketHistory.objects.all():
        if history.actor_discord_id:
            person = get_or_create_person(
                Person, User,
                discord_id=history.actor_discord_id,
                discord_username=history.actor_username or "",
            )
            if person:
                history.actor = person
                history.save()


def noop(apps, schema_editor):
    """No-op for reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticket_assigned_to_ticket_resolved_by_and_more'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_ticket_fks, noop),
        migrations.RunPython(populate_comment_fks, noop),
        migrations.RunPython(populate_history_fks, noop),
    ]
