# Generated by Django 5.0.14 on 2025-11-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0002_copy_data_from_core"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ip_address",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
