# Generated by Django 5.1.14 on 2025-11-29 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_helper_activated_at_and_more'),
        ('team', '0001_initial'),
        ('ticketing', '0003_populate_person_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticketing_t_assigne_4fd9d4_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to_authentik_user_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to_authentik_username',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to_discord_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to_discord_username',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resolved_by_authentik_user_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resolved_by_authentik_username',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resolved_by_discord_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resolved_by_discord_username',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='author_discord_id',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='actor_discord_id',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='actor_username',
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to'], name='ticketing_t_assigne_bc985f_idx'),
        ),
    ]
