# Generated by Django 5.2.11 on 2026-02-08 00:56

from django.conf import settings
from django.db import migrations, models


def delete_empty_ticket_numbers(apps, schema_editor):
    Ticket = apps.get_model("ticketing", "Ticket")
    deleted, _ = Ticket.objects.filter(ticket_number="").delete()
    if deleted:
        print(f"  Deleted {deleted} ticket(s) with empty ticket_number")


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_migrate_helper_data'),
        ('ticketing', '0006_change_fks_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_empty_ticket_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('ticket_number', ''), _negated=True), name='ticket_number_not_empty'),
        ),
    ]
