# Generated by Django 5.2.11 on 2026-02-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_ticket_ticket_number_not_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('optional_fields', models.JSONField(blank=True, default=list)),
                ('variable_points', models.BooleanField(default=False)),
                ('variable_cost_note', models.TextField(blank=True)),
                ('min_points', models.IntegerField(default=0)),
                ('max_points', models.IntegerField(default=0)),
                ('user_creatable', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
            },
        ),
    ]
