# Generated by Django 5.2.11 on 2026-02-15 15:09

from django.db import migrations


def seed_categories(apps, schema_editor):
    TicketCategory = apps.get_model("ticketing", "TicketCategory")
    categories = [
        {
            "id": 1,
            "display_name": "Service Scoring Validation",
            "points": 0,
            "required_fields": ["service_name"],
            "optional_fields": ["description"],
            "variable_points": False,
            "variable_cost_note": "",
            "min_points": 0,
            "max_points": 0,
            "user_creatable": True,
            "sort_order": 0,
        },
        {
            "id": 2,
            "display_name": "Box Reset / Scrub",
            "points": 60,
            "required_fields": ["hostname", "ip_address"],
            "optional_fields": [],
            "variable_points": False,
            "variable_cost_note": "",
            "min_points": 0,
            "max_points": 0,
            "user_creatable": True,
            "sort_order": 1,
        },
        {
            "id": 3,
            "display_name": "Scoring Service Check",
            "points": 10,
            "required_fields": ["service_name"],
            "optional_fields": [],
            "variable_points": False,
            "variable_cost_note": "",
            "min_points": 0,
            "max_points": 0,
            "user_creatable": True,
            "sort_order": 2,
        },
        {
            "id": 4,
            "display_name": "Black Team Phone Consultation",
            "points": 100,
            "required_fields": ["description"],
            "optional_fields": [],
            "variable_points": False,
            "variable_cost_note": "",
            "min_points": 0,
            "max_points": 0,
            "user_creatable": True,
            "sort_order": 3,
        },
        {
            "id": 5,
            "display_name": "Black Team Hands-on Consultation",
            "points": 200,
            "required_fields": ["hostname", "description"],
            "optional_fields": [],
            "variable_points": False,
            "variable_cost_note": "If consultation exceeded 45 minutes, ticket lead will manually adjust to 300 points",
            "min_points": 0,
            "max_points": 0,
            "user_creatable": True,
            "sort_order": 4,
        },
        {
            "id": 6,
            "display_name": "Other / General Issue",
            "points": 0,
            "required_fields": ["description"],
            "optional_fields": [],
            "variable_points": True,
            "variable_cost_note": "",
            "min_points": 0,
            "max_points": 0,
            "user_creatable": True,
            "sort_order": 5,
        },
    ]
    for cat in categories:
        TicketCategory.objects.create(**cat)


def reverse_seed(apps, schema_editor):
    TicketCategory = apps.get_model("ticketing", "TicketCategory")
    TicketCategory.objects.filter(id__in=[1, 2, 3, 4, 5, 6]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0008_ticketcategory"),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
