# Generated by Django 5.2.11 on 2026-02-15 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0009_seed_ticket_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="category_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="ticketing.ticketcategory",
            ),
        ),
    ]
