# Generated by Django 5.2.11 on 2026-02-15 15:10

from django.db import migrations

CATEGORY_MAP = {
    "service-scoring-validation": 1,
    "box-reset": 2,
    "scoring-service-check": 3,
    "blackteam-phone-consultation": 4,
    "blackteam-handson-consultation": 5,
    "other": 6,
}


def populate_fk(apps, schema_editor):
    Ticket = apps.get_model("ticketing", "Ticket")
    TicketCategory = apps.get_model("ticketing", "TicketCategory")
    for old_key, cat_id in CATEGORY_MAP.items():
        try:
            category = TicketCategory.objects.get(id=cat_id)
            Ticket.objects.filter(category=old_key).update(category_fk=category)
        except TicketCategory.DoesNotExist:
            pass


def reverse_fk(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0010_add_ticket_category_fk"),
    ]

    operations = [
        migrations.RunPython(populate_fk, reverse_fk),
    ]
