# Generated by Django 5.2.11 on 2026-02-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0011_populate_ticket_category_fk"),
    ]

    operations = [
        # Remove old index on CharField category + status
        migrations.RemoveIndex(
            model_name="ticket",
            name="ticketing_t_categor_77881b_idx",
        ),
        # Remove old CharField
        migrations.RemoveField(
            model_name="ticket",
            name="category",
        ),
        # Rename FK field to category
        migrations.RenameField(
            model_name="ticket",
            old_name="category_fk",
            new_name="category",
        ),
        # Re-add index on new FK category + status (new name due to FK column)
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["category", "status"], name="ticketing_t_categor_26b782_idx"),
        ),
    ]
