# Generated by Django 5.2.11 on 2026-02-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_swap_ticket_category_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['sort_order', 'display_name'], 'verbose_name_plural': 'ticket categories'},
        ),
    ]
