# Generated by Django 5.2.12 on 2026-03-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0013_alter_ticketcategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='verification_notes',
            new_name='approval_notes',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='points_verified_at',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='points_verified',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='points_verified_by',
            new_name='approved_by',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
