# Generated by Django 5.1.14 on 2025-11-26 04:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Competition name (e.g., 'SWCCDC 2025')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Competition overview and rules')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current competition state', max_length=20)),
                ('scheduled_start_time', models.DateTimeField(help_text='Planned competition start time')),
                ('scheduled_end_time', models.DateTimeField(help_text='Planned competition end time')),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='When competition actually started', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='When competition actually ended', null=True)),
                ('paused_at', models.DateTimeField(blank=True, help_text='When competition was paused (if currently paused)', null=True)),
                ('total_paused_duration', models.DurationField(default=datetime.timedelta, help_text='Total accumulated pause time')),
                ('team_count', models.IntegerField(default=50, help_text='Number of competing teams (1-50)')),
                ('ticketing_enabled', models.BooleanField(default=True, help_text='Allow teams to submit tickets')),
                ('scoring_enabled', models.BooleanField(default=True, help_text='Enable Quotient scoring integration')),
                ('quotient_competition_id', models.CharField(blank=True, help_text='Quotient competition UUID for scoring', max_length=50)),
                ('discord_announcement_channel_id', models.BigIntegerField(blank=True, help_text='Discord channel for competition announcements', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this competition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'db_table': 'competition_competition',
                'ordering': ['-scheduled_start_time'],
            },
        ),
    ]
