# Generated by Django 5.0.14 on 2025-11-06 09:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Competition name (e.g., 'SWCCDC 2025')",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Competition overview and rules"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current competition state",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_start_time",
                    models.DateTimeField(help_text="Planned competition start time"),
                ),
                (
                    "scheduled_end_time",
                    models.DateTimeField(help_text="Planned competition end time"),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When competition actually started",
                        null=True,
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When competition actually ended",
                        null=True,
                    ),
                ),
                (
                    "paused_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When competition was paused (if currently paused)",
                        null=True,
                    ),
                ),
                (
                    "total_paused_duration",
                    models.DurationField(
                        default=datetime.timedelta,
                        help_text="Total accumulated pause time",
                    ),
                ),
                (
                    "team_count",
                    models.IntegerField(
                        default=50, help_text="Number of competing teams (1-50)"
                    ),
                ),
                (
                    "ticketing_enabled",
                    models.BooleanField(
                        default=True, help_text="Allow teams to submit tickets"
                    ),
                ),
                (
                    "scoring_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable Quotient scoring integration"
                    ),
                ),
                (
                    "quotient_competition_id",
                    models.CharField(
                        blank=True,
                        help_text="Quotient competition UUID for scoring",
                        max_length=50,
                    ),
                ),
                (
                    "discord_announcement_channel_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord channel for competition announcements",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this competition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition",
                "verbose_name_plural": "Competitions",
                "db_table": "competition_competition",
                "ordering": ["-scheduled_start_time"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Phase name (e.g., 'Day 1', 'Finals')", max_length=100
                    ),
                ),
                (
                    "phase_type",
                    models.CharField(
                        choices=[
                            ("qualification", "Qualification"),
                            ("regional", "Regional"),
                            ("semifinals", "Semifinals"),
                            ("finals", "Finals"),
                            ("practice", "Practice"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "phase_number",
                    models.IntegerField(default=1, help_text="Phase sequence number"),
                ),
                ("start_time", models.DateTimeField(help_text="Phase start time")),
                ("end_time", models.DateTimeField(help_text="Phase end time")),
                ("description", models.TextField(blank=True)),
                (
                    "is_scored",
                    models.BooleanField(
                        default=True, help_text="Include this phase in scoring"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        help_text="Parent competition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="competition.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Phase",
                "verbose_name_plural": "Competition Phases",
                "db_table": "competition_phase",
                "ordering": ["competition", "phase_number"],
                "unique_together": {("competition", "phase_number")},
            },
        ),
    ]
