# Generated by Django 5.1.14 on 2025-11-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='slug',
        ),
    ]
