# Generated by Django 5.0.14 on 2025-11-12 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompetitionPhase",
        ),
    ]
