# Generated by Django 5.1.14 on 2025-11-24 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0002_remove_competition_phase"),
        ("person", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentHelper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_id",
                    models.BigIntegerField(
                        db_index=True, help_text="Discord user ID (cached from Person)"
                    ),
                ),
                (
                    "discord_username",
                    models.CharField(
                        help_text="Discord username (cached from Person)",
                        max_length=100,
                    ),
                ),
                (
                    "authentik_username",
                    models.CharField(
                        db_index=True,
                        help_text="Authentik username (cached from Person)",
                        max_length=150,
                    ),
                ),
                (
                    "discord_role_name",
                    models.CharField(
                        help_text='Discord role name (e.g., "UCI Invitationals 2026")',
                        max_length=100,
                    ),
                ),
                (
                    "discord_role_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord role ID (snowflake) once assigned",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current helper status",
                        max_length=20,
                    ),
                ),
                (
                    "custom_start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Custom start time (overrides competition start)",
                        null=True,
                    ),
                ),
                (
                    "custom_end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Custom end time (overrides competition end)",
                        null=True,
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When role was actually assigned",
                        null=True,
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When role was actually removed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revoke_reason",
                    models.TextField(
                        blank=True, help_text="Reason for manual revocation"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        help_text="Competition or invitational this helper is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_helpers",
                        to="competition.competition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this helper assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_helpers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person assigned as helper",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helper_assignments",
                        to="person.person",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who revoked this helper assignment (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_helpers_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Helper",
                "verbose_name_plural": "Student Helpers",
                "db_table": "competition_student_helper",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["competition", "status"],
                        name="competition_competi_76a215_idx",
                    ),
                    models.Index(
                        fields=["person", "status"],
                        name="competition_person__f9dd87_idx",
                    ),
                    models.Index(
                        fields=["discord_id", "status"],
                        name="competition_discord_bf119b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "active"])),
                        fields=("person", "competition"),
                        name="competition_unique_active_helper_assignment",
                    )
                ],
            },
        ),
    ]
