# Generated by Django 5.1.14 on 2025-11-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_studenthelper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
