# Generated by Django 5.1.14 on 2025-11-20 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(help_text='Django user account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('authentik_username', models.CharField(db_index=True, help_text='Preferred username from Authentik', max_length=150)),
                ('authentik_user_id', models.CharField(blank=True, db_index=True, help_text='Authentik user UUID (pk)', max_length=50, null=True, unique=True)),
                ('authentik_email', models.EmailField(blank=True, help_text='Email from Authentik', max_length=254)),
                ('authentik_groups', models.JSONField(default=list, help_text='Cached list of Authentik group names')),
                ('discord_id', models.BigIntegerField(blank=True, db_index=True, help_text='Discord user ID (snowflake) if linked', null=True, unique=True)),
                ('discord_username', models.CharField(blank=True, help_text='Discord username (not guaranteed unique)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'person_person',
                'ordering': ['authentik_username'],
            },
        ),
    ]
