# Generated by Django 5.1.14 on 2025-11-28 21:54

from django.db import migrations, models


def migrate_student_helpers(apps, schema_editor):
    """Copy StudentHelper data to Person model."""
    StudentHelper = apps.get_model('person', 'StudentHelper')
    Person = apps.get_model('person', 'Person')

    for helper in StudentHelper.objects.all():
        try:
            person = helper.person
            # Only update if helper is active or person doesn't have helper data yet
            if helper.status == 'active' or not person.helper_role_name:
                person.is_student_helper = (helper.status == 'active')
                person.helper_role_name = helper.discord_role_name
                person.helper_role_id = helper.discord_role_id
                person.helper_activated_at = helper.activated_at
                person.helper_deactivated_at = helper.deactivated_at
                person.helper_removal_reason = helper.removal_reason
                person.save()
        except Exception:
            pass  # Skip if person doesn't exist


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_studenthelper_from_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='helper_activated_at',
            field=models.DateTimeField(blank=True, help_text='When helper access was granted', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='helper_deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When helper access was revoked', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='helper_removal_reason',
            field=models.TextField(blank=True, help_text='Reason for helper access removal'),
        ),
        migrations.AddField(
            model_name='person',
            name='helper_role_id',
            field=models.BigIntegerField(blank=True, help_text='Discord role ID (snowflake)', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='helper_role_name',
            field=models.CharField(blank=True, help_text='Discord role name (e.g., "UCI Invitationals 2026")', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='is_student_helper',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this person is currently a student helper'),
        ),
        migrations.RunPython(migrate_student_helpers, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='StudentHelper',
        ),
    ]
