# Generated by Django 5.1.15 on 2025-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_helper_activated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='authentik_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Authentik user UUID (pk)', max_length=64, null=True, unique=True),
        ),
    ]
