# Generated by Django 5.1.14 on 2025-11-23 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team", "0008_enable_nov15_and_later_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Packet title/description", max_length=255
                    ),
                ),
                (
                    "file_data",
                    models.BinaryField(help_text="Packet file stored as binary data"),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "mime_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("distributing", "Distributing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_distribution_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to automatically distribute this packet",
                        null=True,
                    ),
                ),
                (
                    "actual_distribution_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When distribution actually started",
                        null=True,
                    ),
                ),
                (
                    "send_via_email",
                    models.BooleanField(
                        default=True, help_text="Send packet via email to team contacts"
                    ),
                ),
                (
                    "web_access_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Allow teams to download from web interface",
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(help_text="Username who uploaded", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this packet"
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Packet",
                "verbose_name_plural": "Team Packets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PacketDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "email_sent_to",
                    models.EmailField(
                        blank=True,
                        help_text="Email address where packet was sent",
                        max_length=254,
                    ),
                ),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_error_message", models.TextField(blank=True)),
                ("web_access_enabled", models.BooleanField(default=True)),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="First time packet was downloaded",
                        null=True,
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "downloaded_by",
                    models.CharField(
                        blank=True,
                        help_text="Username who last downloaded",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.team"
                    ),
                ),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="packets.teampacket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Packet Distribution",
                "verbose_name_plural": "Packet Distributions",
                "ordering": ["team__team_number"],
                "indexes": [
                    models.Index(
                        fields=["packet", "email_status"],
                        name="packets_pac_packet__d7cbad_idx",
                    ),
                    models.Index(
                        fields=["packet", "team"], name="packets_pac_packet__f3eee6_idx"
                    ),
                ],
                "unique_together": {("packet", "team")},
            },
        ),
    ]
