# Generated by Django 5.1.14 on 2025-11-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teampacket",
            name="scheduled_distribution_time",
        ),
        migrations.AlterField(
            model_name="teampacket",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("distributing", "Distributing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
