# Generated by Django 5.1.15 on 2025-12-10 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0002_remove_scheduled_distribution'),
        ('registration', '0002_add_events_and_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampacket',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optionally associate packet with a specific event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packets', to='registration.event'),
        ),
    ]
