# Generated by Django 5.2.11 on 2026-02-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0003_add_event_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampacket',
            name='team_extras',
            field=models.JSONField(blank=True, default=dict, help_text='Per-team data for emails, keyed by team number'),
        ),
    ]
