# Generated by Django 5.2.11 on 2026-02-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0005_rename_teampacket_to_packet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Packet', 'verbose_name_plural': 'Packets'},
        ),
    ]
