# Generated by Django 5.0.14 on 2025-11-06 08:46

from django.db import migrations


def copy_team_data(apps, schema_editor):
    """Copy data from core app tables to team app tables."""
    # Get models from both apps
    CoreTeam = apps.get_model("core", "Team")
    TeamTeam = apps.get_model("team", "Team")

    CoreDiscordLink = apps.get_model("core", "DiscordLink")
    TeamDiscordLink = apps.get_model("team", "DiscordLink")

    CoreLinkToken = apps.get_model("core", "LinkToken")
    TeamLinkToken = apps.get_model("team", "LinkToken")

    CoreLinkAttempt = apps.get_model("core", "LinkAttempt")
    TeamLinkAttempt = apps.get_model("team", "LinkAttempt")

    CoreLinkRateLimit = apps.get_model("core", "LinkRateLimit")
    TeamLinkRateLimit = apps.get_model("team", "LinkRateLimit")

    CoreSchoolInfo = apps.get_model("core", "SchoolInfo")
    TeamSchoolInfo = apps.get_model("team", "SchoolInfo")

    # Step 1: Copy Team records (no foreign keys)
    team_id_mapping = {}
    for core_team in CoreTeam.objects.all():
        new_team = TeamTeam.objects.create(
            id=core_team.id,  # Preserve primary key
            team_number=core_team.team_number,
            team_name=core_team.team_name,
            authentik_group=core_team.authentik_group,
            discord_role_id=core_team.discord_role_id,
            discord_category_id=core_team.discord_category_id,
            max_members=core_team.max_members,
            ticket_counter=core_team.ticket_counter,
            is_active=core_team.is_active,
            created_at=core_team.created_at,
            updated_at=core_team.updated_at,
        )
        team_id_mapping[core_team.id] = new_team.id

    # Step 2: Copy DiscordLink records (has foreign key to Team)
    for core_link in CoreDiscordLink.objects.all():
        team_id = team_id_mapping.get(core_link.team_id) if core_link.team_id else None
        TeamDiscordLink.objects.create(
            id=core_link.id,  # Preserve primary key
            discord_id=core_link.discord_id,
            discord_username=core_link.discord_username,
            authentik_username=core_link.authentik_username,
            authentik_user_id=core_link.authentik_user_id,
            team_id=team_id,
            is_active=core_link.is_active,
            linked_at=core_link.linked_at,
            unlinked_at=core_link.unlinked_at,
        )

    # Step 3: Copy LinkToken records (no foreign keys)
    for core_token in CoreLinkToken.objects.all():
        TeamLinkToken.objects.create(
            id=core_token.id,  # Preserve primary key
            token=core_token.token,
            discord_id=core_token.discord_id,
            discord_username=core_token.discord_username,
            used=core_token.used,
            expires_at=core_token.expires_at,
            created_at=core_token.created_at,
        )

    # Step 4: Copy LinkAttempt records (has foreign key to Team)
    for core_attempt in CoreLinkAttempt.objects.all():
        team_id = (
            team_id_mapping.get(core_attempt.team_id) if core_attempt.team_id else None
        )
        TeamLinkAttempt.objects.create(
            id=core_attempt.id,  # Preserve primary key
            discord_id=core_attempt.discord_id,
            discord_username=core_attempt.discord_username,
            authentik_username=core_attempt.authentik_username,
            team_id=team_id,
            success=core_attempt.success,
            failure_reason=core_attempt.failure_reason,
            created_at=core_attempt.created_at,
        )

    # Step 5: Copy LinkRateLimit records (no foreign keys)
    for core_rate_limit in CoreLinkRateLimit.objects.all():
        TeamLinkRateLimit.objects.create(
            id=core_rate_limit.id,  # Preserve primary key
            discord_id=core_rate_limit.discord_id,
            attempted_at=core_rate_limit.attempted_at,
        )

    # Step 6: Copy SchoolInfo records (has foreign key to Team)
    for core_school in CoreSchoolInfo.objects.all():
        team_id = (
            team_id_mapping.get(core_school.team_id) if core_school.team_id else None
        )
        TeamSchoolInfo.objects.create(
            id=core_school.id,  # Preserve primary key
            team_id=team_id,
            school_name=core_school.school_name,
            contact_email=core_school.contact_email,
            secondary_email=core_school.secondary_email,
            notes=core_school.notes,
            created_at=core_school.created_at,
            updated_at=core_school.updated_at,
            updated_by=core_school.updated_by,
        )


def reverse_copy(apps, schema_editor):
    """Reverse migration - delete copied data from team app."""
    TeamTeam = apps.get_model("team", "Team")
    TeamDiscordLink = apps.get_model("team", "DiscordLink")
    TeamLinkToken = apps.get_model("team", "LinkToken")
    TeamLinkAttempt = apps.get_model("team", "LinkAttempt")
    TeamLinkRateLimit = apps.get_model("team", "LinkRateLimit")
    TeamSchoolInfo = apps.get_model("team", "SchoolInfo")

    # Delete in reverse order of foreign key dependencies
    TeamSchoolInfo.objects.all().delete()
    TeamLinkRateLimit.objects.all().delete()
    TeamLinkAttempt.objects.all().delete()
    TeamLinkToken.objects.all().delete()
    TeamDiscordLink.objects.all().delete()
    TeamTeam.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
        (
            "core",
            "0015_initialize_ticket_counters",
        ),  # Last core migration before team split
    ]

    operations = [
        migrations.RunPython(copy_team_data, reverse_copy),
    ]
