# Generated by Django 5.0.14 on 2025-11-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0004_cleanup_duplicate_authentik_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="authentik_group",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="discordlink",
            index=models.Index(
                fields=["authentik_user_id", "is_active"],
                name="team_discor_authent_81456e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="discordlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("authentik_user_id",),
                name="team_unique_active_authentik_link",
            ),
        ),
    ]
