# Generated by Django 5.1.15 on 2025-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_legacy_authentik_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordlink',
            name='helper_activated_at',
            field=models.DateTimeField(blank=True, help_text='When helper access was granted', null=True),
        ),
        migrations.AddField(
            model_name='discordlink',
            name='helper_deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When helper access was revoked', null=True),
        ),
        migrations.AddField(
            model_name='discordlink',
            name='helper_removal_reason',
            field=models.TextField(blank=True, help_text='Reason for helper access removal'),
        ),
        migrations.AddField(
            model_name='discordlink',
            name='helper_role_id',
            field=models.BigIntegerField(blank=True, help_text='Discord role ID (snowflake)', null=True),
        ),
        migrations.AddField(
            model_name='discordlink',
            name='helper_role_name',
            field=models.CharField(blank=True, help_text='Discord role name (e.g., "UCI Invitationals 2026")', max_length=100),
        ),
        migrations.AddField(
            model_name='discordlink',
            name='is_student_helper',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this person is currently a student helper'),
        ),
    ]
