# Generated by Django 5.0.14 on 2025-11-15 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0005_alter_team_authentik_group_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="discordlink",
            name="team_unique_active_authentik_link",
        ),
    ]
