# Generated by Django 5.0.14 on 2025-11-15 15:46

from typing import Any
from django.db import migrations


def reactivate_team_links(apps: Any, schema_editor: Any) -> None:
    """
    Reactivate Discord links that were incorrectly deactivated by migration 0004.
    Blue teams share a single Authentik account, so multiple Discord users should
    be able to link to the same authentik_user_id.
    """
    DiscordLink = apps.get_model("team", "DiscordLink")

    # Reactivate all links that were deactivated and have a team
    # (team links are the ones that share authentik_user_id)
    # But skip any where the discord_id already has an active link
    deactivated_team_links = DiscordLink.objects.filter(
        is_active=False,
        team__isnull=False,
        unlinked_at__isnull=False,
    )

    count = 0
    for link in deactivated_team_links:
        # Check if this discord_id already has an active link
        existing_active = DiscordLink.objects.filter(
            discord_id=link.discord_id, is_active=True
        ).exists()

        if not existing_active:
            link.is_active = True
            link.unlinked_at = None
            link.save()
            count += 1

    if count > 0:
        print(f"Reactivated {count} team Discord links")


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0006_remove_unique_authentik_constraint"),
    ]

    operations = [
        migrations.RunPython(
            reactivate_team_links,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
