# Generated by Django 5.0.14 on 2025-11-15

from django.db import migrations
from datetime import datetime


def enable_nov15_and_later_links(apps, schema_editor):
    """
    Enable all blue team users who linked on/after November 15, 2025
    and disable all those who linked before then.

    This ensures only the most recent links (after the bug fix) are active.

    IMPORTANT: This only affects blue team members (team__isnull=False).
    Admin and support users (team=NULL) are NOT affected.
    """
    DiscordLink = apps.get_model("team", "DiscordLink")

    # Import timezone handling
    from django.utils import timezone

    # Set cutoff date to November 15, 2025 00:00:00 UTC
    cutoff_date = timezone.make_aware(datetime(2025, 11, 15))

    # Deactivate all BLUE TEAM links created BEFORE Nov 15
    # (team__isnull=False ensures we only touch team members, not admin/support)
    links_before = DiscordLink.objects.filter(
        team__isnull=False,  # Only blue team members
        linked_at__lt=cutoff_date,
        is_active=True,
    )

    deactivated_count = links_before.update(is_active=False, unlinked_at=timezone.now())

    # Activate all BLUE TEAM links created ON/AFTER Nov 15
    # (team__isnull=False ensures we only touch team members, not admin/support)
    # But only if the discord_id doesn't already have an active link
    links_after = DiscordLink.objects.filter(
        team__isnull=False,  # Only blue team members
        linked_at__gte=cutoff_date,
        is_active=False,
    )

    activated_count = 0
    for link in links_after:
        # Check if this discord_id already has an active link
        existing_active = DiscordLink.objects.filter(
            discord_id=link.discord_id, is_active=True
        ).exists()

        if not existing_active:
            link.is_active = True
            link.unlinked_at = None
            link.save()
            activated_count += 1

    print(f"Deactivated {deactivated_count} blue team links from before Nov 15")
    print(f"Activated {activated_count} blue team links from Nov 15 onwards")
    print("Admin/support users (non-team) were NOT affected")


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0007_reactivate_team_links"),
    ]

    operations = [
        migrations.RunPython(
            enable_nov15_and_later_links,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
