# Generated by Django 5.0.14 on 2025-10-18 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("admin_user", models.CharField(max_length=255)),
                ("target_entity", models.CharField(max_length=50)),
                ("target_id", models.BigIntegerField()),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DashboardUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("needs_update", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("update_scheduled_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_number", models.IntegerField(unique=True)),
                ("team_name", models.CharField(max_length=100)),
                ("authentik_group", models.CharField(max_length=255)),
                ("discord_role_id", models.BigIntegerField(blank=True, null=True)),
                ("discord_category_id", models.BigIntegerField(blank=True, null=True)),
                ("max_members", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["team_number"],
            },
        ),
        migrations.CreateModel(
            name="LinkToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("discord_id", models.BigIntegerField()),
                ("discord_username", models.CharField(max_length=255)),
                ("used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["token", "used", "expires_at"],
                        name="core_linkto_token_1f9c69_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("service_name", models.CharField(blank=True, max_length=100)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("claimed", "Claimed"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("priority", models.CharField(default="normal", max_length=20)),
                (
                    "assigned_to_discord_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "assigned_to_discord_username",
                    models.CharField(blank=True, max_length=255),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by_discord_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("resolved_by_username", models.CharField(blank=True, max_length=255)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("duration_notes", models.TextField(blank=True)),
                ("points_charged", models.IntegerField(default=0)),
                ("dedup_group", models.CharField(blank=True, max_length=50)),
                ("points_waived", models.BooleanField(default=False)),
                (
                    "discord_thread_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("discord_channel_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "thread_archive_scheduled_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ticket",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PointAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("reason", models.TextField()),
                ("adjustment_type", models.CharField(max_length=50)),
                ("adjusted_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="core.team",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscordTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("create_thread", "Create Thread"),
                            ("update_embed", "Update Embed"),
                            ("update_dashboard", "Update Dashboard"),
                            ("archive_thread", "Archive Thread"),
                            ("send_message", "Send Message"),
                            ("post_comment", "Post Comment to Thread"),
                            ("broadcast_message", "Broadcast Message"),
                            ("assign_role", "Assign Team Role"),
                            ("remove_role", "Remove Team Role"),
                            ("setup_team_infrastructure", "Setup Team Infrastructure"),
                            ("log_to_channel", "Log to Ops Channel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=5)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_data", models.BinaryField()),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("uploaded_by", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_type", models.CharField(max_length=20)),
                ("author_name", models.CharField(max_length=255)),
                ("author_discord_id", models.BigIntegerField(blank=True, null=True)),
                ("comment_text", models.TextField()),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("discord_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["posted_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("actor_discord_id", models.BigIntegerField(null=True)),
                ("actor_username", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LinkAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_id", models.BigIntegerField()),
                ("discord_username", models.CharField(max_length=255)),
                ("authentik_username", models.CharField(max_length=255)),
                ("success", models.BooleanField()),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_linkat_created_8a3df7_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiscordLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_id", models.BigIntegerField(unique=True)),
                ("discord_username", models.CharField(max_length=255)),
                ("authentik_username", models.CharField(max_length=255)),
                ("authentik_user_id", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("unlinked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["discord_id", "is_active"],
                        name="core_discor_discord_44e7e7_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["team", "status"], name="core_ticket_team_id_d7e6c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["category", "status"], name="core_ticket_categor_ef4901_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assigned_to_discord_id"], name="core_ticket_assigne_13b6a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["discord_thread_id"], name="core_ticket_discord_83ad06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discordtask",
            index=models.Index(
                fields=["status", "next_retry_at"], name="core_discor_status_6ec6f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discordtask",
            index=models.Index(
                fields=["task_type", "status"], name="core_discor_task_ty_70e867_idx"
            ),
        ),
    ]
