# Generated by Django 5.1.14 on 2025-11-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('admin_user', models.CharField(max_length=255)),
                ('target_entity', models.CharField(max_length=50)),
                ('target_id', models.BigIntegerField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_team_members', models.IntegerField(default=10, help_text='Maximum members per team')),
                ('competition_start_time', models.DateTimeField(blank=True, help_text='When applications should be enabled', null=True)),
                ('competition_end_time', models.DateTimeField(blank=True, help_text='When applications should be disabled', null=True)),
                ('applications_enabled', models.BooleanField(default=False, help_text='Whether applications are currently enabled')),
                ('controlled_applications', models.JSONField(default=list, help_text="List of Authentik application slugs to enable/disable (e.g., ['netbird', 'scoring'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_check', models.DateTimeField(blank=True, help_text='Last time background task checked', null=True)),
            ],
            options={
                'verbose_name': 'Competition Configuration',
                'verbose_name_plural': 'Competition Configuration',
            },
        ),
        migrations.CreateModel(
            name='DashboardUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_update', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('update_scheduled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('create_thread', 'Create Thread'), ('update_embed', 'Update Embed'), ('update_dashboard', 'Update Dashboard'), ('archive_thread', 'Archive Thread'), ('send_message', 'Send Message'), ('post_comment', 'Post Comment to Thread'), ('broadcast_message', 'Broadcast Message'), ('assign_role', 'Assign Team Role'), ('remove_role', 'Remove Team Role'), ('setup_team_infrastructure', 'Setup Team Infrastructure'), ('log_to_channel', 'Log to Ops Channel')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='core_discor_status_6ec6f0_idx'), models.Index(fields=['task_type', 'status'], name='core_discor_task_ty_70e867_idx')],
            },
        ),
    ]
