# Generated by Django 5.1.15 on 2025-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionconfig',
            name='controlled_applications',
            field=models.JSONField(default=list, help_text="List of Authentik application slugs to enable/disable (e.g., ['netbird', 'scoring'])"),
        ),
    ]
