# Generated by Django 5.0.14 on 2025-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition_start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When applications should be enabled",
                        null=True,
                    ),
                ),
                (
                    "applications_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether applications are currently enabled",
                    ),
                ),
                (
                    "controlled_applications",
                    models.JSONField(
                        default=list,
                        help_text="List of Authentik application slugs to enable/disable (e.g., ['netbird', 'scoring'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_check",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time background task checked",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Configuration",
                "verbose_name_plural": "Competition Configuration",
            },
        ),
        migrations.RenameIndex(
            model_name="ticket",
            new_name="core_ticket_assigne_da1914_idx",
            old_name="core_ticket_assigne_13b6a0_idx",
        ),
    ]
