# Generated by Django 5.1.15 on 2025-12-07 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_competitionconfig_controlled_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('authentik_id', models.CharField(db_index=True, help_text='Authentik user UUID (sub claim)', max_length=64, unique=True)),
                ('groups', models.JSONField(default=list, help_text='List of Authentik group names')),
            ],
            options={
                'verbose_name': 'User Groups',
                'verbose_name_plural': 'User Groups',
            },
        ),
    ]
