# Generated by Django 5.0.14 on 2025-10-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_update_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("secondary_email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "School Information",
                "verbose_name_plural": "School Information",
                "ordering": ["team__team_number"],
            },
        ),
        migrations.RenameIndex(
            model_name="commentratelimit",
            new_name="core_commen_ticket__27466c_idx",
            old_name="core_commen_ticket__idx",
        ),
        migrations.RenameIndex(
            model_name="commentratelimit",
            new_name="core_commen_discord_d0526b_idx",
            old_name="core_commen_discord_idx",
        ),
        migrations.RenameIndex(
            model_name="linkratelimit",
            new_name="core_linkra_discord_d4ff70_idx",
            old_name="core_linkra_discord_5a8b9c_idx",
        ),
        migrations.AddField(
            model_name="schoolinfo",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_info",
                to="core.team",
            ),
        ),
    ]
