# Generated by Django 5.2.9 on 2025-12-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_migrate_to_usergroups'),
        ('team', '0006_migrate_helper_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_announcements', to='team.team')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
