# Generated by Django 5.2.10 on 2026-01-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_queued_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionconfig',
            name='status_channel_id',
            field=models.BigIntegerField(blank=True, help_text='Discord channel ID for competition status display', null=True),
        ),
        migrations.AddField(
            model_name='competitionconfig',
            name='status_message_id',
            field=models.BigIntegerField(blank=True, help_text='Discord message ID for status embed (updated in place)', null=True),
        ),
    ]
