# Generated by Django 5.2.11 on 2026-02-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_status_channel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionconfig',
            name='controlled_applications',
            field=models.JSONField(default=list, help_text="List of Authentik application slugs to enable/disable (e.g., ['scoring', 'quotient2', 'semaphore'])"),
        ),
        migrations.AlterField(
            model_name='discordtask',
            name='task_type',
            field=models.CharField(choices=[('create_thread', 'Create Thread'), ('update_embed', 'Update Embed'), ('update_dashboard', 'Update Dashboard'), ('archive_thread', 'Archive Thread'), ('send_message', 'Send Message'), ('post_comment', 'Post Comment to Thread'), ('broadcast_message', 'Broadcast Message'), ('assign_role', 'Assign Team Role'), ('remove_role', 'Remove Team Role'), ('setup_team_infrastructure', 'Setup Team Infrastructure'), ('log_to_channel', 'Log to Ops Channel'), ('post_ticket_update', 'Post Ticket Update to Thread')], max_length=50),
        ),
    ]
