# Generated by Django 5.2.12 on 2026-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_post_ticket_update_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordtask',
            name='task_type',
            field=models.CharField(choices=[('create_thread', 'Create Thread'), ('update_embed', 'Update Embed'), ('update_dashboard', 'Update Dashboard'), ('archive_thread', 'Archive Thread'), ('send_message', 'Send Message'), ('post_comment', 'Post Comment to Thread'), ('broadcast_message', 'Broadcast Message'), ('assign_role', 'Assign Team Role'), ('assign_group_roles', 'Assign Group-Based Roles'), ('remove_role', 'Remove Team Role'), ('setup_team_infrastructure', 'Setup Team Infrastructure'), ('log_to_channel', 'Log to Ops Channel'), ('post_ticket_update', 'Post Ticket Update to Thread'), ('ticket_created_web', 'Ticket Created via Web'), ('sync_roles', 'Sync Roles Between Guilds')], max_length=50),
        ),
    ]
