# Generated by Django 5.0.14 on 2025-10-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_add_authentik_attribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("claimed", "Claimed"),
                    ("resolved", "Resolved"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
