# Generated by Django 5.0.14 on 2025-11-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordlink",
            name="discord_id",
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="discordlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("discord_id",),
                name="unique_active_discord_link",
            ),
        ),
    ]
