# Generated by Django 5.0.14 on 2025-11-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_discordlink_discord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ticket_counter',
            field=models.IntegerField(default=0),
        ),
    ]
