# Generated by Django 5.0.14 on 2025-11-05 07:17

from typing import Any

from django.db import migrations


def initialize_ticket_counters(apps: Any, schema_editor: Any) -> None:
    Team = apps.get_model("core", "Team")
    Ticket = apps.get_model("core", "Ticket")

    for team in Team.objects.all():
        tickets = Ticket.objects.filter(team=team).order_by("-created_at")
        if tickets.exists():
            latest_ticket = tickets.first()
            last_seq = int(latest_ticket.ticket_number.split("-")[1])
            team.ticket_counter = last_seq
        else:
            team.ticket_counter = 0
        team.save(update_fields=["ticket_counter"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_add_ticket_counter"),
    ]

    operations = [
        migrations.RunPython(initialize_ticket_counters, migrations.RunPython.noop),
    ]
