# Generated by Django 5.0.14 on 2025-11-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_initialize_ticket_counters"),
        ("team", "0002_copy_data_from_core"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discordlink",
            name="team",
        ),
        migrations.RemoveField(
            model_name="linkattempt",
            name="team",
        ),
        migrations.DeleteModel(
            name="LinkRateLimit",
        ),
        migrations.DeleteModel(
            name="LinkToken",
        ),
        migrations.RemoveField(
            model_name="schoolinfo",
            name="team",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="team.team",
            ),
        ),
        migrations.DeleteModel(
            name="DiscordLink",
        ),
        migrations.DeleteModel(
            name="LinkAttempt",
        ),
        migrations.DeleteModel(
            name="SchoolInfo",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
