# Generated by Django 5.0.14 on 2025-11-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_discordlink_team_remove_linkattempt_team_and_more"),
        ("ticketing", "0002_copy_data_from_core"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="team",
        ),
        migrations.RemoveField(
            model_name="tickethistory",
            name="ticket",
        ),
        migrations.RemoveField(
            model_name="ticketattachment",
            name="ticket",
        ),
        migrations.RemoveField(
            model_name="ticketcomment",
            name="ticket",
        ),
        migrations.AlterField(
            model_name="discordtask",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ticketing.ticket",
            ),
        ),
        migrations.DeleteModel(
            name="CommentRateLimit",
        ),
        migrations.DeleteModel(
            name="TicketHistory",
        ),
        migrations.DeleteModel(
            name="TicketAttachment",
        ),
        migrations.DeleteModel(
            name="TicketComment",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
