# Generated by Django 5.0.14 on 2025-11-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_ticket_team_remove_tickethistory_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionconfig",
            name="competition_end_time",
            field=models.DateTimeField(
                blank=True, help_text="When applications should be disabled", null=True
            ),
        ),
    ]
