# Generated by Django 5.0.14 on 2025-11-15

from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def sync_discord_roles(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Sync Discord roles for all active blue team members.

    Creates Discord tasks to:
    1. Assign group-based roles (including Blueteam role)
    2. Assign team-specific role

    This ensures Discord roles match the active DiscordLink records
    after the Nov 15 link activation migration.
    """
    DiscordLink = apps.get_model("team", "DiscordLink")
    DiscordTask = apps.get_model("core", "DiscordTask")
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")

    # Get all active blue team members
    active_team_links = DiscordLink.objects.filter(
        team__isnull=False, is_active=True
    ).select_related("team")

    task_count = 0

    for link in active_team_links:
        # Get Authentik groups from SocialAccount
        # The extra_data field contains the OAuth response with groups
        try:
            social_account = SocialAccount.objects.get(
                provider="openid_connect",
                extra_data__preferred_username=link.authentik_username,
            )
            groups = social_account.extra_data.get("groups", [])
        except SocialAccount.DoesNotExist:
            # If no social account found, use default blue team group
            groups = [f"WCComps_BlueTeam{link.team.team_number:02d}"]
        except SocialAccount.MultipleObjectsReturned:
            # If multiple accounts (shouldn't happen), get the first
            social_account = SocialAccount.objects.filter(
                provider="openid_connect",
                extra_data__preferred_username=link.authentik_username,
            ).first()
            groups = social_account.extra_data.get("groups", [])

        # Create task to assign group-based roles
        DiscordTask.objects.create(
            task_type="assign_group_roles",
            payload={"discord_id": link.discord_id, "authentik_groups": groups},
            status="pending",
        )
        task_count += 1

        # Create task to assign team role
        DiscordTask.objects.create(
            task_type="assign_role",
            payload={
                "discord_id": link.discord_id,
                "team_number": link.team.team_number,
            },
            status="pending",
        )
        task_count += 1

    print(
        f"Created {task_count} Discord tasks to sync roles for {active_team_links.count()} active team members"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_competitionconfig_competition_end_time"),
        ("team", "0008_enable_nov15_and_later_links"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.RunPython(
            sync_discord_roles,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
