# Generated by Django 5.1.15 on 2025-12-10 04:16

import django.db.models.deletion
import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('team', '0006_migrate_helper_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='phone',
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='edit_token',
            field=models.CharField(default=registration.models.generate_edit_token, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='edit_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('invitational', 'Invitational'), ('qualifier', 'Qualifier'), ('regional', 'Regional'), ('state', 'State')], max_length=20)),
                ('event_number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('registration_open', models.BooleanField(default=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_finalized', models.BooleanField(default=False)),
                ('max_teams', models.IntegerField(default=50)),
                ('reminder_days', models.JSONField(default=list)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registration.season')),
            ],
            options={
                'ordering': ['season', 'date'],
            },
        ),
        migrations.CreateModel(
            name='EventTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('credentials_sent_at', models.DateTimeField(blank=True, null=True)),
                ('password_generated', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='registration.event')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='registration.teamregistration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='team.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'registration'), name='unique_assignment_per_registration'), models.UniqueConstraint(fields=('event', 'team'), name='unique_team_per_event')],
            },
        ),
        migrations.CreateModel(
            name='RegistrationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', 'Team Captain'), ('co_captain', 'Co-Captain'), ('coach', 'Coach/Faculty Advisor'), ('site_judge', 'Site Judge')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='registration.teamregistration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('registration', 'role'), name='unique_contact_role_per_registration')],
            },
        ),
        migrations.CreateModel(
            name='RegistrationEventEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='registration.event')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_enrollments', to='registration.teamregistration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('registration', 'event'), name='unique_enrollment_per_registration')],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('season', 'event_type', 'event_number'), name='unique_event_per_season'),
        ),
    ]
