# Generated by Django 5.2.9 on 2025-12-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_add_events_and_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='region',
            field=models.CharField(choices=[('wrccdc', 'Western Regional (WRCCDC)'), ('prccdc', 'Pacific Rim (PRCCDC)'), ('mwccdc', 'Midwest (MWCCDC)'), ('rmccdc', 'Rocky Mountain (RMCCDC)'), ('swccdc', 'Southwest (SWCCDC)'), ('neccdc', 'Northeast (NECCDC)'), ('maccdc', 'Mid-Atlantic (MACCDC)'), ('seccdc', 'Southeast (SECCDC)'), ('at_large', 'At-Large')], default='wrccdc', max_length=20),
        ),
    ]
