# Generated by Django 5.1.14 on 2025-11-23 23:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackTeamAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for point adjustment')),
                ('point_adjustment', models.DecimalField(decimal_places=2, help_text='Point adjustment (positive or negative)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_team_adjustments', to='competition.competition')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_adjustments_submitted', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_team_adjustments', to='team.team')),
            ],
            options={
                'verbose_name': 'Black Team Adjustment',
                'verbose_name_plural': 'Black Team Adjustments',
                'db_table': 'black_team_adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_description', models.TextField(help_text='Description of detected attack')),
                ('source_ip', models.GenericIPAddressField(help_text='Attacker source IP')),
                ('destination_ip', models.GenericIPAddressField(help_text="Victim IP (team's system)")),
                ('affected_box', models.CharField(blank=True, max_length=100)),
                ('affected_service', models.CharField(blank=True, max_length=100)),
                ('attack_detected_at', models.DateTimeField(help_text='When the attack was detected')),
                ('attack_mitigated', models.BooleanField(default=False, help_text='Attack was successfully mitigated')),
                ('evidence_notes', models.TextField(blank=True)),
                ('gold_team_reviewed', models.BooleanField(default=False)),
                ('points_returned', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Points awarded for detecting/reporting this incident', max_digits=10)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='competition.competition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_submitted', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Team submitting the incident report', on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='team.team')),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'db_table': 'incident_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scoring/incidents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='scoring.incidentreport')),
            ],
            options={
                'db_table': 'incident_screenshot',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrangeTeamBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of security improvement')),
                ('points_awarded', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orange_team_bonuses', to='competition.competition')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orange_bonuses_submitted', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orange_team_bonuses', to='team.team')),
            ],
            options={
                'verbose_name': 'Orange Team Bonus',
                'verbose_name_plural': 'Orange Team Bonuses',
                'db_table': 'orange_team_bonus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotientMetadataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes', models.JSONField(default=list, help_text='List of boxes from Quotient metadata')),
                ('services', models.JSONField(default=list, help_text='List of services from Quotient metadata')),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('team_count', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotient_metadata', to='competition.competition')),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotient Metadata Cache',
                'verbose_name_plural': 'Quotient Metadata Caches',
                'db_table': 'quotient_metadata_cache',
            },
        ),
        migrations.CreateModel(
            name='RedTeamFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_vector', models.TextField(help_text='Description of the attack/exploit')),
                ('source_ip', models.GenericIPAddressField(help_text='Red team source IP')),
                ('destination_ip_template', models.CharField(blank=True, help_text='IP template (e.g., 10.100.1X.22 where X is team number)', max_length=50)),
                ('affected_box', models.CharField(blank=True, max_length=100)),
                ('affected_service', models.CharField(blank=True, max_length=100)),
                ('universally_attempted', models.BooleanField(default=False, help_text='Attack was attempted against all teams')),
                ('persistence_established', models.BooleanField(default=False, help_text='Persistence was established on target')),
                ('points_per_team', models.DecimalField(decimal_places=2, help_text='Points deducted per affected team (will be applied as negative)', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_teams', models.ManyToManyField(help_text='Teams affected by this finding', related_name='red_team_findings', to='team.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_team_findings', to='competition.competition')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_findings_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Red Team Finding',
                'verbose_name_plural': 'Red Team Findings',
                'db_table': 'red_team_finding',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='matched_to_red_finding',
            field=models.ForeignKey(blank=True, help_text='Red team finding this incident matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_incident_reports', to='scoring.redteamfinding'),
        ),
        migrations.CreateModel(
            name='RedTeamScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scoring/red_team/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='scoring.redteamfinding')),
            ],
            options={
                'db_table': 'red_team_screenshot',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_weight', models.DecimalField(decimal_places=2, default=Decimal('0.60'), help_text='Weight for service uptime scores', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('inject_weight', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Weight for inject scores', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('orange_weight', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Weight for orange team bonuses', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('red_weight', models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Weight for red team deductions (applied as negative)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('incident_recovery_weight', models.DecimalField(decimal_places=2, default=Decimal('0.12'), help_text='Weight for points returned from matched incident reports', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('sla_weight', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Weight for SLA penalties (applied as negative)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_template', to='competition.competition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_template_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scoring Template',
                'verbose_name_plural': 'Scoring Templates',
                'db_table': 'scoring_template',
            },
        ),
        migrations.CreateModel(
            name='ServiceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sla_violations', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='SLA penalty points (stored as negative)', max_digits=10)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_scores', to='competition.competition')),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_scores', to='team.team')),
            ],
            options={
                'verbose_name': 'Service Score',
                'verbose_name_plural': 'Service Scores',
                'db_table': 'service_score',
                'ordering': ['team__team_number'],
            },
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('inject_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('orange_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('red_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('incident_recovery_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sla_penalties', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('black_adjustments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_scores', to='competition.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_scores', to='team.team')),
            ],
            options={
                'verbose_name': 'Final Score',
                'verbose_name_plural': 'Final Scores',
                'db_table': 'final_score',
                'ordering': ['-total_score', 'team__team_number'],
                'indexes': [models.Index(fields=['competition', '-total_score'], name='final_score_competi_26f314_idx')],
                'unique_together': {('competition', 'team')},
            },
        ),
        migrations.CreateModel(
            name='InjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inject_id', models.CharField(help_text='Quotient inject ID', max_length=100)),
                ('inject_name', models.CharField(max_length=200)),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_awarded', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True, help_text='Grader notes')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inject_grades', to='competition.competition')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injects_graded', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inject_grades', to='team.team')),
            ],
            options={
                'verbose_name': 'Inject Grade',
                'verbose_name_plural': 'Inject Grades',
                'db_table': 'inject_grade',
                'ordering': ['inject_name', 'team__team_number'],
                'unique_together': {('competition', 'team', 'inject_id')},
            },
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['competition', 'team'], name='incident_re_competi_4376d5_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['gold_team_reviewed'], name='incident_re_gold_te_3ffc22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicescore',
            unique_together={('competition', 'team')},
        ),
    ]
