# Generated by Django 5.1.14 on 2025-11-24 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='finalscore',
            name='final_score_competi_26f314_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidentreport',
            name='incident_re_competi_4376d5_idx',
        ),
        migrations.RemoveField(
            model_name='blackteamadjustment',
            name='competition',
        ),
        migrations.AlterUniqueTogether(
            name='finalscore',
            unique_together={('team',)},
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='competition',
        ),
        migrations.AlterUniqueTogether(
            name='injectgrade',
            unique_together={('team', 'inject_id')},
        ),
        migrations.RemoveField(
            model_name='orangeteambonus',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='quotientmetadatacache',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='redteamfinding',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='competition',
        ),
        migrations.AlterUniqueTogether(
            name='servicescore',
            unique_together={('team',)},
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['team'], name='incident_re_team_id_a84098_idx'),
        ),
        migrations.RemoveField(
            model_name='finalscore',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='injectgrade',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='servicescore',
            name='competition',
        ),
    ]
