# Generated by Django 5.1.14 on 2025-11-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='attack_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='destination_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='source_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
