# Generated by Django 5.1.14 on 2025-11-28 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_make_destination_ip_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redteamfinding',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this finding was approved', null=True),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Gold Team member who approved this finding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_findings_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this finding has been approved by Gold Team'),
        ),
    ]
