# Generated by Django 5.1.14 on 2025-11-24 03:59

import django.core.validators
import scoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_remove_finalscore_final_score_competi_26f314_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentscreenshot',
            name='image',
            field=models.ImageField(upload_to='scoring/incidents/%Y/%m/%d/', validators=[scoring.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='redteamscreenshot',
            name='image',
            field=models.ImageField(upload_to='scoring/red_team/%Y/%m/%d/', validators=[scoring.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
