# Generated by Django 5.1.14 on 2025-11-28 00:54

import django.db.models.deletion
from django.db import migrations, models


def create_initial_check_types(apps, schema_editor):
    """Create initial orange check types."""
    OrangeCheckType = apps.get_model("scoring", "OrangeCheckType")
    initial_types = [
        "Customer service call answered",
        "Network diagram completed",
        "Password reset assistance",
        "Rule violation",
        "Professional behavior bonus",
    ]

    for type_name in initial_types:
        OrangeCheckType.objects.get_or_create(name=type_name)


def reverse_create_initial_check_types(apps, schema_editor):
    """Remove initial check types."""
    OrangeCheckType = apps.get_model("scoring", "OrangeCheckType")
    initial_types = [
        "Customer service call answered",
        "Network diagram completed",
        "Password reset assistance",
        "Rule violation",
        "Professional behavior bonus",
    ]

    OrangeCheckType.objects.filter(name__in=initial_types).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_redteamfinding_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeCheckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orange Check Type',
                'verbose_name_plural': 'Orange Check Types',
                'db_table': 'orange_check_type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='orangeteambonus',
            name='check_type',
            field=models.ForeignKey(blank=True, help_text='Category of this check (optional for backwards compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='scoring.orangechecktype'),
        ),
        migrations.RunPython(create_initial_check_types, reverse_create_initial_check_types),
    ]
