# Generated by Django 5.1.14 on 2025-11-28 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_redteamfinding_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeCheckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orange Check Type',
                'verbose_name_plural': 'Orange Check Types',
                'db_table': 'orange_check_type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='orangeteambonus',
            name='check_type',
            field=models.ForeignKey(blank=True, help_text='Category of this check (optional for backwards compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='scoring.orangechecktype'),
        ),
    ]
