# Generated by Django 5.1.14 on 2025-11-24 04:05

import scoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_screenshot_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentscreenshot',
            name='image',
            field=models.ImageField(upload_to='scoring/incidents/%Y/%m/%d/', validators=[scoring.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='redteamscreenshot',
            name='image',
            field=models.ImageField(upload_to='scoring/red_team/%Y/%m/%d/', validators=[scoring.models.validate_file_size]),
        ),
    ]
