# Generated by Django 5.1.14 on 2025-11-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_update_screenshot_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redteamfinding',
            name='points_per_team',
            field=models.DecimalField(decimal_places=2, help_text='Points deducted per affected team (assigned by Gold Team)', max_digits=10),
        ),
    ]
