# Generated by Django 5.1.14 on 2025-11-28 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_add_orange_check_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orangeteambonus',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this bonus was approved', null=True),
        ),
        migrations.AddField(
            model_name='orangeteambonus',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this bonus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orange_bonuses_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orangeteambonus',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this bonus has been approved'),
        ),
    ]
