# Generated by Django 5.1.14 on 2025-11-28 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_orangeteambonus_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='injectgrade',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the grade was approved', null=True),
        ),
        migrations.AddField(
            model_name='injectgrade',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injects_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='injectgrade',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Grade has been approved by supervisor'),
        ),
    ]
