# Generated by Django 5.1.14 on 2025-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_update_points_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orangeteambonus',
            name='description',
            field=models.TextField(help_text='Description of why points are awarded'),
        ),
    ]
