# Generated by Django 5.1.14 on 2025-11-24 09:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_alter_orangeteambonus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringtemplate',
            name='inject_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.4'), help_text='Multiplier applied to inject scores (e.g., 1.4 = 140%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='orange_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.5'), help_text='Multiplier applied to orange team scores (e.g., 5.5 = 550%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
