# Generated by Django 5.1.14 on 2025-11-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_add_score_multipliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='incident_recovery_weight',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='inject_weight',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='orange_weight',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='red_weight',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='service_weight',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='sla_weight',
        ),
    ]
