# Generated by Django 5.1.14 on 2025-11-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_orangechecktype_default_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectgrade',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
