# Generated by Django 5.1.14 on 2025-11-25 02:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_remove_unused_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringtemplate',
            name='recovery_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Multiplier applied to incident recovery points (e.g., 1.0 = 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='red_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Multiplier applied to red team deductions (e.g., 1.0 = 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='service_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Multiplier applied to service scores (e.g., 1.0 = 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='sla_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Multiplier applied to SLA penalties (e.g., 1.0 = 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
