# Generated by Django 5.1.15 on 2025-12-10 04:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_add_events_and_contacts'),
        ('scoring', '0009_convert_screenshots_to_binary'),
        ('team', '0006_migrate_helper_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackteamadjustment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_team_adjustments', to='registration.event'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='registration.event'),
        ),
        migrations.AddField(
            model_name='injectgrade',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inject_grades', to='registration.event'),
        ),
        migrations.AddField(
            model_name='orangeteambonus',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orange_team_bonuses', to='registration.event'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_team_findings', to='registration.event'),
        ),
        migrations.AddField(
            model_name='servicescore',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_scores', to='registration.event'),
        ),
        migrations.CreateModel(
            name='EventScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('inject_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('orange_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('red_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('incident_recovery_points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sla_penalties', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('black_adjustments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('scorecard_sent_at', models.DateTimeField(blank=True, help_text='When PDF score card was emailed', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='registration.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_scores', to='team.team')),
                ('team_assignment', models.ForeignKey(blank=True, help_text='Link to registration for traceability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_scores', to='registration.eventteamassignment')),
            ],
            options={
                'verbose_name': 'Event Score',
                'verbose_name_plural': 'Event Scores',
                'db_table': 'event_score',
                'ordering': ['-total_score', 'team__team_number'],
                'unique_together': {('team', 'event')},
            },
        ),
    ]
