# Generated by Django 5.1.14 on 2025-11-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0009_add_all_multipliers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orangeteambonus',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orange Team Adjustment', 'verbose_name_plural': 'Orange Team Adjustments'},
        ),
        migrations.AlterField(
            model_name='orangeteambonus',
            name='description',
            field=models.TextField(help_text='Description of why points are adjusted (positive or negative)'),
        ),
        migrations.AlterField(
            model_name='orangeteambonus',
            name='points_awarded',
            field=models.DecimalField(decimal_places=2, help_text='Points to add (positive) or deduct (negative)', max_digits=10),
        ),
    ]
