# Generated by Django 5.1.15 on 2025-12-12 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_add_event_fk_and_event_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='redteamfinding',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Red team source IP (use this OR source_ip_pool)', null=True),
        ),
        migrations.CreateModel(
            name='RedTeamIPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_addresses', models.TextField(help_text='Newline or comma-separated IP addresses used for rotating attacks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Red Team IP Pool',
                'verbose_name_plural': 'Red Team IP Pools',
                'db_table': 'red_team_ip_pool',
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='source_ip_pool',
            field=models.ForeignKey(blank=True, help_text='Pool of rotating source IPs (use this OR source_ip)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='scoring.redteamippool'),
        ),
    ]
