# Generated by Django 5.1.15 on 2025-12-12 05:27

from django.db import migrations, models


def migrate_redteamfinding_affected_box(apps, schema_editor):
    """Convert affected_box string to affected_boxes list for RedTeamFinding."""
    RedTeamFinding = apps.get_model('scoring', 'RedTeamFinding')
    for finding in RedTeamFinding.objects.all():
        if finding.affected_box:
            finding.affected_boxes = [finding.affected_box]
        else:
            finding.affected_boxes = []
        finding.save(update_fields=['affected_boxes'])


def reverse_redteamfinding_affected_box(apps, schema_editor):
    """Reverse: convert affected_boxes list back to affected_box string."""
    RedTeamFinding = apps.get_model('scoring', 'RedTeamFinding')
    for finding in RedTeamFinding.objects.all():
        if finding.affected_boxes:
            finding.affected_box = finding.affected_boxes[0]
        else:
            finding.affected_box = ''
        finding.save(update_fields=['affected_box'])


def migrate_incidentreport_affected_box(apps, schema_editor):
    """Convert affected_box string to affected_boxes list for IncidentReport."""
    IncidentReport = apps.get_model('scoring', 'IncidentReport')
    for report in IncidentReport.objects.all():
        if report.affected_box:
            report.affected_boxes = [report.affected_box]
        else:
            report.affected_boxes = []
        report.save(update_fields=['affected_boxes'])


def reverse_incidentreport_affected_box(apps, schema_editor):
    """Reverse: convert affected_boxes list back to affected_box string."""
    IncidentReport = apps.get_model('scoring', 'IncidentReport')
    for report in IncidentReport.objects.all():
        if report.affected_boxes:
            report.affected_box = report.affected_boxes[0]
        else:
            report.affected_box = ''
        report.save(update_fields=['affected_box'])


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0011_add_red_team_ip_pool'),
    ]

    operations = [
        # RedTeamFinding: Add new affected_boxes field
        migrations.AddField(
            model_name='redteamfinding',
            name='affected_boxes',
            field=models.JSONField(blank=True, default=list, help_text='List of affected box names'),
        ),
        # RedTeamFinding: Migrate data
        migrations.RunPython(migrate_redteamfinding_affected_box, reverse_redteamfinding_affected_box),
        # RedTeamFinding: Remove old field
        migrations.RemoveField(
            model_name='redteamfinding',
            name='affected_box',
        ),
        # IncidentReport: Add new affected_boxes field
        migrations.AddField(
            model_name='incidentreport',
            name='affected_boxes',
            field=models.JSONField(blank=True, default=list, help_text='List of affected box names'),
        ),
        # IncidentReport: Migrate data
        migrations.RunPython(migrate_incidentreport_affected_box, reverse_incidentreport_affected_box),
        # IncidentReport: Remove old field
        migrations.RemoveField(
            model_name='incidentreport',
            name='affected_box',
        ),
    ]
