# Generated by Django 5.1.15 on 2025-12-12 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Common CCDC attack types with descriptions
ATTACK_TYPES = [
    ("Default Credentials", "Login using default/unchanged passwords (admin/admin, root/toor, etc.)"),
    ("Weak Credentials", "Login using weak/guessable passwords (password123, company name, etc.)"),
    ("Password Spray", "Attempting common passwords across multiple accounts"),
    ("Credential Stuffing", "Using leaked/stolen credentials from other breaches"),
    ("Brute Force", "Automated password guessing attack"),
    ("SQL Injection", "Injecting SQL commands through user input"),
    ("Command Injection", "Injecting OS commands through user input"),
    ("Remote Code Execution", "Executing arbitrary code on target system"),
    ("Local File Inclusion", "Reading local files through vulnerable application"),
    ("Remote File Inclusion", "Including remote malicious files"),
    ("Path Traversal", "Accessing files outside intended directory"),
    ("Cross-Site Scripting (XSS)", "Injecting malicious scripts into web pages"),
    ("Cross-Site Request Forgery (CSRF)", "Tricking users into performing unintended actions"),
    ("Privilege Escalation", "Gaining higher privileges than initially obtained"),
    ("Lateral Movement", "Moving between systems after initial compromise"),
    ("Persistence", "Establishing continued access (backdoors, scheduled tasks, etc.)"),
    ("Data Exfiltration", "Extracting sensitive data from compromised systems"),
    ("Service Exploitation", "Exploiting vulnerabilities in running services"),
    ("Misconfiguration Exploit", "Exploiting insecure configurations"),
    ("Denial of Service", "Disrupting service availability"),
    ("Man-in-the-Middle", "Intercepting communications between systems"),
    ("DNS Poisoning", "Manipulating DNS responses"),
    ("ARP Spoofing", "Manipulating ARP tables for traffic interception"),
    ("Phishing", "Social engineering via deceptive communications"),
    ("Malware Deployment", "Installing malicious software on target"),
    ("Ransomware", "Encrypting data for ransom"),
    ("Rootkit Installation", "Installing hidden malicious tools"),
    ("Log Tampering", "Modifying or deleting logs to hide activity"),
    ("Account Creation", "Creating unauthorized user accounts"),
    ("Service Manipulation", "Modifying or disabling services"),
    ("Firewall Bypass", "Circumventing firewall rules"),
    ("Other", "Attack type not listed above"),
]


def seed_attack_types(apps, schema_editor):
    """Seed the database with common attack types."""
    AttackType = apps.get_model('scoring', 'AttackType')
    for name, description in ATTACK_TYPES:
        AttackType.objects.get_or_create(
            name=name,
            defaults={'description': description, 'is_active': True}
        )


def remove_attack_types(apps, schema_editor):
    """Remove seeded attack types (reverse migration)."""
    AttackType = apps.get_model('scoring', 'AttackType')
    AttackType.objects.filter(name__in=[name for name, _ in ATTACK_TYPES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_rename_affected_box_to_affected_boxes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Help text for red teamers')),
                ('is_active', models.BooleanField(default=True, help_text='Can be selected for new findings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attack Type',
                'verbose_name_plural': 'Attack Types',
                'db_table': 'attack_type',
                'ordering': ['name'],
            },
        ),
        # Seed attack types
        migrations.RunPython(seed_attack_types, remove_attack_types),
        migrations.AddField(
            model_name='redteamfinding',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='All red teamers who submitted matching findings', related_name='contributed_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='redteamfinding',
            name='attack_vector',
            field=models.TextField(blank=True, help_text='Additional details about the attack (legacy field, use notes instead)'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='attack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='scoring.attacktype'),
        ),
    ]
