# Generated by Django 5.1.15 on 2025-12-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_add_attack_type_and_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='redteamfinding',
            name='credentials_recovered',
            field=models.BooleanField(default=False, help_text='User IDs and passwords recovered (-50 pts)'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='credit_cards_recovered',
            field=models.BooleanField(default=False, help_text='Customer credit card numbers recovered (-50 pts)'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='db_decrypted',
            field=models.BooleanField(default=False, help_text='Database was decrypted (-25 pts additional)'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='encrypted_db_recovered',
            field=models.BooleanField(default=False, help_text='Encrypted customer data/database recovered (-25 pts)'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='pii_recovered',
            field=models.BooleanField(default=False, help_text='PII recovered: name, address, CC# (-200 pts)'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='privilege_escalation',
            field=models.BooleanField(default=False, help_text='User escalated to Root/Admin (-100 pts additional)'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='root_access',
            field=models.BooleanField(default=False, help_text='Root/Administrator level access obtained (-100 pts)'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='sensitive_files_recovered',
            field=models.BooleanField(default=False, help_text='Config files, corporate data recovered (-25 pts)'),
        ),
        migrations.AddField(
            model_name='redteamfinding',
            name='user_access',
            field=models.BooleanField(default=False, help_text='User level access obtained (-25 pts, not scored if root_access)'),
        ),
        migrations.AlterField(
            model_name='redteamfinding',
            name='points_per_team',
            field=models.DecimalField(decimal_places=2, help_text='Points deducted per affected team (auto-calculated from outcomes)', max_digits=10),
        ),
    ]
