# Generated by Django 5.2.11 on 2026-02-04 05:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0015_update_attack_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='inject_multiplier',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='orange_multiplier',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='recovery_multiplier',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='red_multiplier',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='service_multiplier',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='sla_multiplier',
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='inject_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('500'), help_text='Maximum possible inject points', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='inject_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), help_text='Percentage weight for inject responses', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='orange_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Maximum possible orange team points', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='orange_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='Percentage weight for orange team adjustments', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='red_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('200'), help_text='Maximum possible red team deductions', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='red_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='Percentage weight for red team (deductions offset by recovery)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='service_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='Maximum possible service points (from Quotient)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='service_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('40'), help_text='Percentage weight for service uptime (includes SLA penalties)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
