# Generated by Django 5.2.11 on 2026-02-20 04:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_add_region_field'),
        ('scoring', '0016_scoring_percentage_weights'),
        ('team', '0006_migrate_helper_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='inject_weight',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='orange_weight',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='red_max',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='red_weight',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='service_weight',
        ),
        migrations.AddField(
            model_name='eventscore',
            name='point_adjustments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='finalscore',
            name='point_adjustments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='inject_modifier',
            field=models.DecimalField(decimal_places=6, default=Decimal('3.743137'), help_text='Multiplier for raw inject points', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='orange_modifier',
            field=models.DecimalField(decimal_places=6, default=Decimal('35.793750'), help_text='Multiplier for raw orange team points', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='service_modifier',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), help_text='Multiplier for raw service points (typically 1.0)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='servicescore',
            name='point_adjustments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Manual point adjustments (stored as negative)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='scoringtemplate',
            name='inject_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('3060'), help_text='Maximum possible raw inject points', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='scoringtemplate',
            name='orange_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('160'), help_text='Maximum possible raw orange team points', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='scoringtemplate',
            name='service_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('11454'), help_text='Maximum possible raw service points', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Service identifier (e.g., balrog-ntp)', max_length=100)),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='registration.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='team.team')),
            ],
            options={
                'verbose_name': 'Service Detail',
                'verbose_name_plural': 'Service Details',
                'db_table': 'service_detail',
                'ordering': ['service_name', 'team__team_number'],
                'unique_together': {('team', 'event', 'service_name')},
            },
        ),
    ]
