# Generated by Django 5.2.11 on 2026-02-20 05:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0017_remove_scoringtemplate_inject_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='inject_modifier',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='orange_modifier',
        ),
        migrations.RemoveField(
            model_name='scoringtemplate',
            name='service_modifier',
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='inject_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('40'), help_text='Percentage weight for inject responses', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='orange_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), help_text='Percentage weight for orange team adjustments', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='service_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('40'), help_text='Percentage weight for service uptime', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
