# Generated by Django 5.2.11 on 2026-02-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0018_remove_scoringtemplate_inject_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscore',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='Exclude this team from comparative analysis and leaderboard'),
        ),
    ]
