# Generated by Django 5.2.11 on 2026-02-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0019_add_eventscore_is_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='Exclude from comparative analysis and leaderboard'),
        ),
    ]
