# Generated by Django 5.2.11 on 2026-02-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0020_add_finalscore_is_excluded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventScore',
        ),
    ]
