# Generated by Django 5.2.11 on 2026-02-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0021_delete_eventscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InjectGrade",
            new_name="InjectScore",
        ),
    ]
