# Generated by Django 5.2.11 on 2026-02-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0022_rename_injectgrade_to_injectscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrangeTeamBonus",
            new_name="OrangeTeamScore",
        ),
    ]
