# Generated by Django 5.2.11 on 2026-02-21 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_add_region_field'),
        ('scoring', '0023_rename_orangeteambonus_to_orangeteamscore'),
        ('team', '0006_migrate_helper_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injectscore',
            options={'ordering': ['inject_name', 'team__team_number'], 'verbose_name': 'Inject Score', 'verbose_name_plural': 'Inject Scores'},
        ),
        migrations.AlterField(
            model_name='orangeteamscore',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this bonus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orange_scores_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orangeteamscore',
            name='check_type',
            field=models.ForeignKey(blank=True, help_text='Category of this check (optional for backwards compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='scoring.orangechecktype'),
        ),
        migrations.AlterField(
            model_name='orangeteamscore',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orange_team_scores', to='registration.event'),
        ),
        migrations.AlterField(
            model_name='orangeteamscore',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orange_scores_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orangeteamscore',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orange_team_scores', to='team.team'),
        ),
    ]
