# Generated by Django 5.2.11 on 2026-02-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0026_update_redteamscore_related_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finalscore",
            name="black_adjustments",
        ),
        migrations.DeleteModel(
            name="BlackTeamAdjustment",
        ),
    ]
