# Generated by Django 5.2.11 on 2026-02-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0027_remove_blackteamadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orangeteamscore",
            name="check_type",
        ),
        migrations.DeleteModel(
            name="OrangeCheckType",
        ),
    ]
