# Generated by Django 5.2.11 on 2026-02-21 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0028_remove_orangechecktype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redteamscore',
            options={'ordering': ['-created_at'], 'verbose_name': 'Red Team Score', 'verbose_name_plural': 'Red Team Scores'},
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='matched_to_red_score',
            field=models.ForeignKey(blank=True, help_text='Red team score this incident matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_incident_reports', to='scoring.redteamscore'),
        ),
    ]
