# Generated by Django 5.2.11 on 2026-02-21 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0029_alter_redteamscore_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='injectscore',
            name='feedback',
            field=models.TextField(blank=True, help_text='Professional feedback shown to teams on scorecard'),
        ),
        migrations.AddField(
            model_name='injectscore',
            name='feedback_approved',
            field=models.BooleanField(default=False, help_text='Whether feedback has been approved for team viewing'),
        ),
        migrations.AddField(
            model_name='injectscore',
            name='feedback_approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inject_feedback_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
