# Generated by Django 5.2.11 on 2026-02-22 14:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0030_injectscore_feedback_injectscore_feedback_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='uptime',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Uptime percentage (0.0000–1.0000)', max_digits=6),
        ),
    ]
