# Generated by Django 5.2.12 on 2026-03-11 01:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0031_servicedetail_uptime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orangeteamscore',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orange Team Check', 'verbose_name_plural': 'Orange Team Checks'},
        ),
        migrations.AlterField(
            model_name='orangeteamscore',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this check was approved', null=True),
        ),
        migrations.AlterField(
            model_name='orangeteamscore',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this check', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orange_scores_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orangeteamscore',
            name='description',
            field=models.TextField(help_text='Description of the orange team check'),
        ),
        migrations.AlterField(
            model_name='orangeteamscore',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this check has been approved'),
        ),
        migrations.AlterField(
            model_name='scoringtemplate',
            name='orange_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('160'), help_text='Maximum possible raw orange team check points', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='scoringtemplate',
            name='orange_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), help_text='Percentage weight for orange team checks', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
