# Generated by Django 5.2.12 on 2026-03-11 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_add_region_field'),
        ('scoring', '0032_alter_orangeteamscore_options_and_more'),
        ('team', '0006_migrate_helper_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incidentreport',
            name='incident_re_gold_te_3ffc22_idx',
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='reviewer_notes',
            new_name='approval_notes',
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='reviewed_at',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='gold_team_reviewed',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='reviewed_by',
            new_name='approved_by',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['is_approved'], name='incident_re_is_appr_15eb15_idx'),
        ),
    ]
