# Generated by Django 5.2.12 on 2026-03-11 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_orangefollowup'),
        ('scoring', '0033_rename_incident_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orangeteamscore',
            name='orange_check',
            field=models.ForeignKey(blank=True, help_text='Orange check this score was created from (null for manual adjustments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orange_scores', to='challenges.orangecheck'),
        ),
    ]
